server:
  port: 8080
  servlet:
    session:
      timeout: 30m
  tomcat:
    connection-timeout: 30s

## logback
logging:
  level:
    root: ERROR
    web: ERROR
  pattern:
    file: "[prod] %magenta([%d{yyyy:MM:dd HH:mm:ss}]) - %highlight([%level]) - %yellow([%thread]) - %green([%logger{35}]) - %msg%n"
    console: "[prod] %magenta([%d{yyyy:MM:dd HH:mm:ss}]) - %highlight([%level]) - %yellow([%thread]) - %green([%logger{35}]) - %msg%n"

spring:
  profiles:
    active: prod
    include: core